name: Release to GitHub Packages

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com/'
      - name: Enable Corepack
        run: corepack enable
      - name: Set Yarn Berry
        run: corepack prepare yarn@stable --activate
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Extract release notes from CHANGELOG.md
        id: changelog
        run: |
          RELEASE_NOTE=$(awk '/^## /{if(NR!=1)exit;next} NR>1{print}' CHANGELOG.md | awk '/^## /{exit} {print}' | sed '/^$/d')
          echo "RELEASE_NOTE<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_NOTE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.RELEASE_NOTE }}

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 